project:
  type: website
  output-dir: docs
    
website:
  title: "Taller R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Taller de R
        menu:
          - text: Desde cero
            href: Taller/DiaposTallerR.qmd
      
      
format:
  html:
    theme:
      - journal
      - brand
    toc: true